services:
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migration
    volumes:
      - .:/app
    depends_on:
      - mysql
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql-data:/var/lib/mysql      
volumes:
  mysql-data: